project-razor/Pages/OauthClients/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using project_razor.Models;

namespace project_razor.Pages.OauthClients
{
    public class CreateModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public CreateModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public OauthClient OauthClient { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.OauthClients.Add(OauthClient);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/OauthClients/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.OauthClients
{
    public class DeleteModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DeleteModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OauthClient OauthClient { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oauthclient = await _context.OauthClients.FirstOrDefaultAsync(m => m.Id == id);

            if (oauthclient is not null)
            {
                OauthClient = oauthclient;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oauthclient = await _context.OauthClients.FindAsync(id);
            if (oauthclient != null)
            {
                OauthClient = oauthclient;
                _context.OauthClients.Remove(OauthClient);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/OauthClients/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.OauthClients
{
    public class DetailsModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DetailsModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public OauthClient OauthClient { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oauthclient = await _context.OauthClients.FirstOrDefaultAsync(m => m.Id == id);

            if (oauthclient is not null)
            {
                OauthClient = oauthclient;

                return Page();
            }

            return NotFound();
        }
    }
}

project-razor/Pages/OauthClients/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.OauthClients
{
    public class EditModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public EditModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OauthClient OauthClient { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oauthclient =  await _context.OauthClients.FirstOrDefaultAsync(m => m.Id == id);
            if (oauthclient == null)
            {
                return NotFound();
            }
            OauthClient = oauthclient;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(OauthClient).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OauthClientExists(OauthClient.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OauthClientExists(int id)
        {
            return _context.OauthClients.Any(e => e.Id == id);
        }
    }
}

project-razor/Pages/Roles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using project_razor.Models;

namespace project_razor.Pages.Roles
{
    public class CreateModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public CreateModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Role Role { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Roles.Add(Role);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/Roles/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Roles
{
    public class DeleteModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DeleteModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Role Role { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FirstOrDefaultAsync(m => m.Id == id);

            if (role is not null)
            {
                Role = role;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                Role = role;
                _context.Roles.Remove(Role);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/Roles/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Roles
{
    public class DetailsModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DetailsModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public Role Role { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FirstOrDefaultAsync(m => m.Id == id);

            if (role is not null)
            {
                Role = role;

                return Page();
            }

            return NotFound();
        }
    }
}

project-razor/Pages/Roles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Roles
{
    public class EditModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public EditModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Role Role { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role =  await _context.Roles.FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            Role = role;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Role).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoleExists(Role.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

project-razor/Pages/Tokens/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using project_razor.Models;

namespace project_razor.Pages.Tokens
{
    public class CreateModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public CreateModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Token Token { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Tokens.Add(Token);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/Tokens/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Tokens
{
    public class DeleteModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DeleteModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Token Token { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens.FirstOrDefaultAsync(m => m.Id == id);

            if (token is not null)
            {
                Token = token;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens.FindAsync(id);
            if (token != null)
            {
                Token = token;
                _context.Tokens.Remove(Token);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/Tokens/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Tokens
{
    public class DetailsModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public DetailsModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public Token Token { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens.FirstOrDefaultAsync(m => m.Id == id);

            if (token is not null)
            {
                Token = token;

                return Page();
            }

            return NotFound();
        }
    }
}

project-razor/Pages/Tokens/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using project_razor.Models;

namespace project_razor.Pages.Tokens
{
    public class IndexModel : PageModel
    {
        private readonly IamContext _context;

        public IndexModel(IamContext context)
        {
            _context = context;
        }

        public List<Token> MyTokens { get; set; } = new();

        public async Task<IActionResult> OnGetAsync()
        {
            var username = User.Identity?.Name;
            if (string.IsNullOrEmpty(username))
                return Unauthorized();

            MyTokens = await _context.Tokens
                .Where(t => t.Username == username)
                .OrderByDescending(t => t.IssuedAt)
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostRevokeAsync(int id)
        {
            var token = await _context.Tokens.FirstOrDefaultAsync(t => t.Id == id);
            if (token == null || token.Username != User.Identity?.Name)
                return Unauthorized();

            _context.Tokens.Remove(token);
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

project-razor/Pages/Users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using project_razor.Models;

namespace project_razor.Pages.Users
{
    public class CreateModel : PageModel
    {
        private readonly project_razor.Models.IamContext _context;

        public CreateModel(project_razor.Models.IamContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public User User { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Users.Add(User);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

project-razor/Pages/Tokens/Create.cshtml
@page
@model project_razor.Pages.Tokens.CreateModel

        @{
        Layout = null;
        }
        
        <!DOCTYPE html>
        
        <html>
        <head>
        <meta name="viewport" content="width=device-width" />
        <title>Create</title>
        </head>
        <body>
        
    <h4>Token</h4>
    <hr />
    <div class="row">
    <div class="col-md-4">
    <form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Token.AccessToken" class="control-label"></label>
                <input asp-for="Token.AccessToken" class="form-control" />
                <span asp-validation-for="Token.AccessToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Token.IssuedAt" class="control-label"></label>
                <input asp-for="Token.IssuedAt" class="form-control" />
                <span asp-validation-for="Token.IssuedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Token.ExpiresAt" class="control-label"></label>
                <input asp-for="Token.ExpiresAt" class="form-control" />
                <span asp-validation-for="Token.ExpiresAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Token.Username" class="control-label"></label>
                <input asp-for="Token.Username" class="form-control" />
                <span asp-validation-for="Token.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

</body>
</html>

project-razor/Pages/Tokens/Delete.cshtml
@page
@model project_razor.Pages.Tokens.DeleteModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Token</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.AccessToken)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.AccessToken)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.IssuedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.IssuedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.ExpiresAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.ExpiresAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.Username)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Token.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>
</body>
</html>

project-razor/Pages/Tokens/Details.cshtml
@page
@model project_razor.Pages.Tokens.DetailsModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Token</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.AccessToken)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.AccessToken)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.IssuedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.IssuedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.ExpiresAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.ExpiresAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Token.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Token.Username)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Token.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>
</body>
</html>

project-razor/Pages/Tokens/Edit.cshtml
@page
@model project_razor.Pages.Tokens.EditModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Token</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Token.Id" />
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Token.AccessToken" class="control-label"></label>
                <input asp-for="Token.AccessToken" class="form-control" />
                <span asp-validation-for="Token.AccessToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Token.IssuedAt" class="control-label"></label>
                <input asp-for="Token.IssuedAt" class="form-control" />
                <span asp-validation-for="Token.IssuedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Token.ExpiresAt" class="control-label"></label>
                <input asp-for="Token.ExpiresAt" class="form-control" />
                <span asp-validation-for="Token.ExpiresAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Token.Username" class="control-label"></label>
                <input asp-for="Token.Username" class="form-control" />
                <span asp-validation-for="Token.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

</body>
</html>

project-razor/Pages/Tokens/Index.cshtml
@page
@model project_razor.Pages.Tokens.IndexModel
@{
    ViewData["Title"] = "Active Sessions";
}

<h2>Active Sessions</h2>

@if (!Model.MyTokens.Any())
{
    <p>No active sessions.</p>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Client ID</th>
                <th>Issued At</th>
                <th>Expires At</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var token in Model.MyTokens)
            {
                <tr>
                    <td>@token.Audience</td>
                    <td>@token.IssuedAt.ToLocalTime()</td>
                    <td>@token.ExpiresAt.ToLocalTime()</td>
                    <td>
                        <form method="post" asp-page-handler="Revoke">
                            <input type="hidden" name="id" value="@token.Id" />
                            <button type="submit" class="btn btn-sm btn-danger">Revoke</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>
}